# frozen_string_literal: true

require "bundler/gem_tasks"
require "fileutils"
require "rake/testtask"
require "rbconfig"

namespace :native do
  desc "Build the SQLGlot semantic sibling for the current platform"
  task :build do
    ruby File.expand_path("ext/sqlglot_semantics/extconf.rb", __dir__)
  end

  desc "Build a platform gem from the current or supplied native library"
  task package: :build do
    platform = ENV.fetch("PLATFORM") do
      Gem::Platform.local.to_s.sub(/-\d+\z/, "")
    end
    output = File.expand_path("pkg/sqlglot-semantics-#{Sqlglot::Semantics::VERSION}-#{platform}.gem", __dir__)
    FileUtils.mkdir_p(File.dirname(output))

    sh(
      {"SQLGLOT_SEMANTICS_PLATFORM" => platform},
      RbConfig.ruby,
      "-S",
      "gem",
      "build",
      "sqlglot-semantics.gemspec",
      "--output",
      output
    )
  end
end

Rake::TestTask.new(:test => "native:build") do |task|
  task.libs << "lib"
  task.pattern = "test/**/*_test.rb"
end

task default: :test
